# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b625a8330df11617e53c7a2db44865e4d20d8861ed59345b5a5bf90e1b5cefc9814ab51e83299a52e68b4bd6e60760078bd0e76a669b9c08e8bfa014796ac2ef

test:
  secret_key_base: 0919169dd962c201ee66f43814a2ace9e9da630f519f5225473efd188aabce6cd256614219988a0f32351f9af7a37de8cc4403805aebe51ab8c2de5dc98e1fbc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
